# Generated by Django 3.0.5 on 2021-02-13 09:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbUser',
            fields=[
                ('user_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('tag_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(default='', unique=True)),
                ('color', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NoteDB',
            fields=[
                ('note_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True, unique=True)),
                ('body', models.TextField(default='')),
                ('links', models.ManyToManyField(to='api.NoteDB')),
                ('tags', models.ManyToManyField(to='api.NoteTag')),
            ],
        ),
    ]
