# Generated by Django 3.0.8 on 2020-07-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('tag_name', models.TextField(max_length=20, primary_key=True, serialize=False, verbose_name='tag_name')),
                ('tag_color', models.TextField(max_length=10, verbose_name='tag_color')),
            ],
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from', models.TextField(max_length=50, verbose_name='id_from')),
                ('id_to', models.TextField(max_length=50, verbose_name='id_to')),
            ],
            options={
                'unique_together': {('id_from', 'id_to')},
            },
        ),
        migrations.CreateModel(
            name='NoteDB',
            fields=[
                ('id', models.TextField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(max_length=100, verbose_name='name')),
                ('body', models.TextField(verbose_name='body')),
                ('links', models.ManyToManyField(to='api.NoteLink')),
                ('tags', models.ManyToManyField(to='api.NoteTag')),
            ],
        ),
    ]
