# Generated by Django 3.0.8 on 2020-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201008_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='notelink',
            name='link_type',
            field=models.TextField(default='normal', max_length=20, verbose_name='link_type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notelink',
            unique_together={('id_from', 'id_to', 'link_type')},
        ),
    ]
